remove mongodb
ArcBlock/wallet-playground pull request #64
Opened 2020-09-09 09:18 UTC by NateRobinson

2020-09-09 23:01 UTC, wangshijun requested changes

2020-09-09 23:01 UTC, wangshijun commented on package.json
>      "requiredEnvironments": [
这里，我们设置默认值，链接到 playground 和 zinc 链吧

2020-09-10 06:19 UTC, NateRobinson commented
Cause nedb can not work in netlify functions, we decide to fork a new repo "blocklet-wallet-playground" do this update.

2020-09-10 06:19 UTC, closed without merging

2020-09-10 06:23 UTC, NateRobinson commented
https://github.com/ArcBlock/blocklet-wallet-playground